import type { LevelConfig } from './types';
import { generateProceduralLevel } from './solver';

export const CURATED_LEVELS: LevelConfig[] = [
  // --- TUTORIAL / EASY (Levels 1 - 5) ---
  {
    id: 1,
    name: 'First Steps',
    difficulty: 'Easy',
    capacity: 4,
    parMoves: 4,
    tubes: [
      ['ruby-red', 'ruby-red', 'ruby-red', 'sapphire-blue'],
      ['sapphire-blue', 'sapphire-blue', 'sapphire-blue', 'ruby-red'],
      [],
    ],
  },
  {
    id: 2,
    name: 'Gentle Wood',
    difficulty: 'Easy',
    capacity: 4,
    parMoves: 6,
    tubes: [
      ['ruby-red', 'ruby-red', 'sapphire-blue', 'sapphire-blue'],
      ['sapphire-blue', 'sapphire-blue', 'ruby-red', 'ruby-red'],
      [],
    ],
  },
  {
    id: 3,
    name: 'Triple Grove',
    difficulty: 'Easy',
    capacity: 4,
    parMoves: 9,
    tubes: [
      ['emerald-green', 'ruby-red', 'sapphire-blue', 'ruby-red'],
      ['sapphire-blue', 'emerald-green', 'ruby-red', 'emerald-green'],
      ['ruby-red', 'sapphire-blue', 'emerald-green', 'sapphire-blue'],
      [],
      [],
    ],
  },
  {
    id: 4,
    name: 'Amber Glow',
    difficulty: 'Easy',
    capacity: 4,
    parMoves: 10,
    tubes: [
      ['amber-orange', 'sapphire-blue', 'amber-orange', 'ruby-red'],
      ['ruby-red', 'ruby-red', 'sapphire-blue', 'amber-orange'],
      ['sapphire-blue', 'amber-orange', 'ruby-red', 'sapphire-blue'],
      [],
      [],
    ],
  },
  {
    id: 5,
    name: 'Forest Canopy',
    difficulty: 'Easy',
    capacity: 4,
    parMoves: 12,
    tubes: [
      ['emerald-green', 'emerald-green', 'amber-orange', 'sapphire-blue'],
      ['ruby-red', 'sapphire-blue', 'ruby-red', 'amber-orange'],
      ['sapphire-blue', 'ruby-red', 'emerald-green', 'ruby-red'],
      ['amber-orange', 'sapphire-blue', 'emerald-green', 'amber-orange'],
      [],
      [],
    ],
  },

  // --- BEGINNER TO INTERMEDIATE (Levels 6 - 15) ---
  {
    id: 6,
    name: 'Sunny Pine',
    difficulty: 'Medium',
    capacity: 4,
    parMoves: 14,
    tubes: [
      ['golden-yellow', 'ruby-red', 'emerald-green', 'golden-yellow'],
      ['sapphire-blue', 'golden-yellow', 'ruby-red', 'emerald-green'],
      ['emerald-green', 'ruby-red', 'sapphire-blue', 'sapphire-blue'],
      ['ruby-red', 'emerald-green', 'golden-yellow', 'sapphire-blue'],
      [],
      [],
    ],
  },
  {
    id: 7,
    name: 'Amethyst Hollow',
    difficulty: 'Medium',
    capacity: 4,
    parMoves: 16,
    tubes: [
      ['amethyst-purple', 'emerald-green', 'ruby-red', 'amethyst-purple'],
      ['ruby-red', 'amber-orange', 'emerald-green', 'amber-orange'],
      ['emerald-green', 'amethyst-purple', 'ruby-red', 'amethyst-purple'],
      ['amber-orange', 'ruby-red', 'emerald-green', 'amber-orange'],
      [],
      [],
    ],
  },
  {
    id: 8,
    name: 'Whispering Leaves',
    difficulty: 'Medium',
    capacity: 4,
    parMoves: 18,
    tubes: [
      ['sapphire-blue', 'golden-yellow', 'amethyst-purple', 'ruby-red'],
      ['emerald-green', 'ruby-red', 'golden-yellow', 'amethyst-purple'],
      ['amethyst-purple', 'emerald-green', 'sapphire-blue', 'golden-yellow'],
      ['ruby-red', 'sapphire-blue', 'emerald-green', 'emerald-green'],
      ['golden-yellow', 'amethyst-purple', 'ruby-red', 'sapphire-blue'],
      [],
      [],
    ],
  },
  {
    id: 9,
    name: 'Rustic Stack',
    difficulty: 'Medium',
    capacity: 4,
    parMoves: 20,
    tubes: [
      ['amber-orange', 'sakura-pink', 'sapphire-blue', 'ruby-red'],
      ['sakura-pink', 'emerald-green', 'amber-orange', 'sapphire-blue'],
      ['ruby-red', 'emerald-green', 'sakura-pink', 'amber-orange'],
      ['sapphire-blue', 'sakura-pink', 'emerald-green', 'ruby-red'],
      ['emerald-green', 'amber-orange', 'ruby-red', 'sapphire-blue'],
      [],
      [],
    ],
  },
  {
    id: 10,
    name: 'Zen Waterfall',
    difficulty: 'Medium',
    capacity: 4,
    parMoves: 22,
    tubes: [
      ['ocean-cyan', 'golden-yellow', 'ruby-red', 'amethyst-purple'],
      ['ruby-red', 'emerald-green', 'ocean-cyan', 'sakura-pink'],
      ['sakura-pink', 'ocean-cyan', 'golden-yellow', 'emerald-green'],
      ['golden-yellow', 'amethyst-purple', 'sakura-pink', 'ocean-cyan'],
      ['emerald-green', 'ruby-red', 'amethyst-purple', 'golden-yellow'],
      ['amethyst-purple', 'sakura-pink', 'ruby-red', 'emerald-green'],
      [],
      [],
    ],
  },

  // --- INTERMEDIATE (Levels 11 - 20) ---
  {
    id: 11,
    name: 'Cedar Maze',
    difficulty: 'Medium',
    capacity: 4,
    parMoves: 24,
    tubes: [
      ['forest-lime', 'sapphire-blue', 'golden-yellow', 'ruby-red'],
      ['ruby-red', 'amethyst-purple', 'forest-lime', 'ocean-cyan'],
      ['ocean-cyan', 'forest-lime', 'amethyst-purple', 'sapphire-blue'],
      ['golden-yellow', 'sapphire-blue', 'ruby-red', 'amethyst-purple'],
      ['amethyst-purple', 'golden-yellow', 'ocean-cyan', 'forest-lime'],
      ['sapphire-blue', 'ruby-red', 'golden-yellow', 'ocean-cyan'],
      [],
      [],
    ],
  },
  {
    id: 12,
    name: 'Old Oak Sanctuary',
    difficulty: 'Medium',
    capacity: 4,
    parMoves: 25,
    tubes: [
      ['sakura-pink', 'amber-orange', 'forest-lime', 'amethyst-purple'],
      ['emerald-green', 'sakura-pink', 'sapphire-blue', 'amber-orange'],
      ['amethyst-purple', 'emerald-green', 'forest-lime', 'sapphire-blue'],
      ['amber-orange', 'sapphire-blue', 'sakura-pink', 'forest-lime'],
      ['forest-lime', 'amethyst-purple', 'emerald-green', 'sakura-pink'],
      ['sapphire-blue', 'amber-orange', 'amethyst-purple', 'emerald-green'],
      [],
      [],
    ],
  },
  {
    id: 13,
    name: 'Timber Drift',
    difficulty: 'Medium',
    capacity: 4,
    parMoves: 26,
    tubes: [
      ['ocean-cyan', 'ruby-red', 'golden-yellow', 'emerald-green'],
      ['sapphire-blue', 'ocean-cyan', 'amber-orange', 'ruby-red'],
      ['golden-yellow', 'emerald-green', 'sapphire-blue', 'amber-orange'],
      ['emerald-green', 'ruby-red', 'ocean-cyan', 'golden-yellow'],
      ['amber-orange', 'sapphire-blue', 'golden-yellow', 'emerald-green'],
      ['ruby-red', 'ocean-cyan', 'sapphire-blue', 'amber-orange'],
      [],
      [],
    ],
  },
  {
    id: 14,
    name: 'Autumn Breeze',
    difficulty: 'Medium',
    capacity: 4,
    parMoves: 28,
    tubes: [
      ['chocolate-brown', 'ruby-red', 'golden-yellow', 'amber-orange'],
      ['golden-yellow', 'emerald-green', 'chocolate-brown', 'sapphire-blue'],
      ['amber-orange', 'chocolate-brown', 'ruby-red', 'golden-yellow'],
      ['sapphire-blue', 'amber-orange', 'emerald-green', 'chocolate-brown'],
      ['ruby-red', 'sapphire-blue', 'emerald-green', 'amber-orange'],
      ['emerald-green', 'golden-yellow', 'sapphire-blue', 'ruby-red'],
      [],
      [],
    ],
  },
  {
    id: 15,
    name: 'Bamboo Harmony',
    difficulty: 'Hard',
    capacity: 4,
    parMoves: 30,
    tubes: [
      ['forest-lime', 'sakura-pink', 'ocean-cyan', 'ruby-red'],
      ['amethyst-purple', 'forest-lime', 'golden-yellow', 'sakura-pink'],
      ['ocean-cyan', 'golden-yellow', 'ruby-red', 'amethyst-purple'],
      ['golden-yellow', 'ruby-red', 'forest-lime', 'ocean-cyan'],
      ['sakura-pink', 'amethyst-purple', 'ocean-cyan', 'golden-yellow'],
      ['ruby-red', 'sakura-pink', 'amethyst-purple', 'forest-lime'],
      [],
      [],
    ],
  },

  // --- HARD / MASTER (Levels 16 - 30) ---
  {
    id: 16,
    name: 'Maple Cascade',
    difficulty: 'Hard',
    capacity: 4,
    parMoves: 32,
    tubes: [
      ['chocolate-brown', 'forest-lime', 'amber-orange', 'ruby-red'],
      ['sapphire-blue', 'ocean-cyan', 'emerald-green', 'golden-yellow'],
      ['ruby-red', 'chocolate-brown', 'forest-lime', 'amber-orange'],
      ['golden-yellow', 'sapphire-blue', 'ocean-cyan', 'emerald-green'],
      ['amber-orange', 'ruby-red', 'chocolate-brown', 'forest-lime'],
      ['emerald-green', 'golden-yellow', 'sapphire-blue', 'ocean-cyan'],
      ['forest-lime', 'amber-orange', 'ruby-red', 'chocolate-brown'],
      ['ocean-cyan', 'emerald-green', 'golden-yellow', 'sapphire-blue'],
      [],
      [],
    ],
  },
  {
    id: 17,
    name: 'Highland Grove',
    difficulty: 'Hard',
    capacity: 4,
    parMoves: 34,
    tubes: [
      ['sakura-pink', 'amethyst-purple', 'chocolate-brown', 'ocean-cyan'],
      ['amber-orange', 'golden-yellow', 'forest-lime', 'ruby-red'],
      ['ocean-cyan', 'sakura-pink', 'amethyst-purple', 'chocolate-brown'],
      ['ruby-red', 'amber-orange', 'golden-yellow', 'forest-lime'],
      ['chocolate-brown', 'ocean-cyan', 'sakura-pink', 'amethyst-purple'],
      ['forest-lime', 'ruby-red', 'amber-orange', 'golden-yellow'],
      ['amethyst-purple', 'chocolate-brown', 'ocean-cyan', 'sakura-pink'],
      ['golden-yellow', 'forest-lime', 'ruby-red', 'amber-orange'],
      [],
      [],
    ],
  },
  {
    id: 18,
    name: 'Ancient Sequoia',
    difficulty: 'Hard',
    capacity: 4,
    parMoves: 36,
    tubes: [
      ['ruby-red', 'sapphire-blue', 'emerald-green', 'amber-orange'],
      ['golden-yellow', 'amethyst-purple', 'sakura-pink', 'ocean-cyan'],
      ['forest-lime', 'chocolate-brown', 'ruby-red', 'sapphire-blue'],
      ['emerald-green', 'amber-orange', 'golden-yellow', 'amethyst-purple'],
      ['sakura-pink', 'ocean-cyan', 'forest-lime', 'chocolate-brown'],
      ['ruby-red', 'emerald-green', 'golden-yellow', 'sakura-pink'],
      ['sapphire-blue', 'amber-orange', 'amethyst-purple', 'ocean-cyan'],
      ['chocolate-brown', 'forest-lime', 'ruby-red', 'emerald-green'],
      ['sapphire-blue', 'golden-yellow', 'sakura-pink', 'forest-lime'],
      [],
      [],
    ],
  },
  {
    id: 19,
    name: 'Wildwood Enigma',
    difficulty: 'Master',
    capacity: 4,
    parMoves: 40,
    tubes: [
      ['ocean-cyan', 'ruby-red', 'amber-orange', 'emerald-green'],
      ['amethyst-purple', 'forest-lime', 'sapphire-blue', 'golden-yellow'],
      ['chocolate-brown', 'sakura-pink', 'ocean-cyan', 'ruby-red'],
      ['emerald-green', 'amethyst-purple', 'forest-lime', 'sapphire-blue'],
      ['golden-yellow', 'chocolate-brown', 'sakura-pink', 'ocean-cyan'],
      ['ruby-red', 'amber-orange', 'emerald-green', 'amethyst-purple'],
      ['sapphire-blue', 'golden-yellow', 'chocolate-brown', 'sakura-pink'],
      ['forest-lime', 'amber-orange', 'sapphire-blue', 'chocolate-brown'],
      [],
      [],
    ],
  },
  {
    id: 20,
    name: 'Grand Woody Masterpiece',
    difficulty: 'Master',
    capacity: 4,
    parMoves: 45,
    tubes: [
      ['chocolate-brown', 'ocean-cyan', 'sakura-pink', 'golden-yellow'],
      ['forest-lime', 'amethyst-purple', 'sapphire-blue', 'emerald-green'],
      ['amber-orange', 'ruby-red', 'chocolate-brown', 'ocean-cyan'],
      ['sakura-pink', 'golden-yellow', 'forest-lime', 'amethyst-purple'],
      ['sapphire-blue', 'emerald-green', 'amber-orange', 'ruby-red'],
      ['ocean-cyan', 'forest-lime', 'amber-orange', 'sakura-pink'],
      ['golden-yellow', 'chocolate-brown', 'amethyst-purple', 'sapphire-blue'],
      ['emerald-green', 'ruby-red', 'golden-yellow', 'chocolate-brown'],
      [],
      [],
    ],
  },
];

// --- 10 SPECIAL HIDDEN / SECRET MYSTERY LEVELS ---
export const HIDDEN_LEVELS: LevelConfig[] = [
  {
    id: 101,
    name: 'Secret Chamber: Emerald Relic',
    isSecret: true,
    difficulty: 'Hidden',
    capacity: 4,
    parMoves: 28,
    tubes: [
      ['emerald-green', 'golden-yellow', 'ocean-cyan', 'emerald-green'],
      ['ocean-cyan', 'emerald-green', 'golden-yellow', 'amethyst-purple'],
      ['amethyst-purple', 'ocean-cyan', 'golden-yellow', 'emerald-green'],
      ['golden-yellow', 'amethyst-purple', 'ocean-cyan', 'amethyst-purple'],
      [],
      [],
    ],
  },
  {
    id: 102,
    name: 'Secret Chamber: Amber Sunstone',
    isSecret: true,
    difficulty: 'Hidden',
    capacity: 4,
    parMoves: 32,
    tubes: [
      ['amber-orange', 'ruby-red', 'chocolate-brown', 'amber-orange'],
      ['golden-yellow', 'amber-orange', 'ruby-red', 'chocolate-brown'],
      ['chocolate-brown', 'golden-yellow', 'ruby-red', 'amber-orange'],
      ['ruby-red', 'chocolate-brown', 'golden-yellow', 'golden-yellow'],
      [],
      [],
    ],
  },
  {
    id: 103,
    name: 'Secret Chamber: Deep Amethyst Crypt',
    isSecret: true,
    difficulty: 'Hidden',
    capacity: 4,
    parMoves: 35,
    tubes: [
      ['amethyst-purple', 'sakura-pink', 'sapphire-blue', 'ocean-cyan'],
      ['ocean-cyan', 'amethyst-purple', 'sakura-pink', 'sapphire-blue'],
      ['sapphire-blue', 'ocean-cyan', 'amethyst-purple', 'sakura-pink'],
      ['sakura-pink', 'sapphire-blue', 'ocean-cyan', 'amethyst-purple'],
      [],
      [],
    ],
  },
  {
    id: 104,
    name: 'Secret Chamber: Redwood Vault',
    isSecret: true,
    difficulty: 'Hidden',
    capacity: 4,
    parMoves: 38,
    tubes: [
      ['chocolate-brown', 'forest-lime', 'amber-orange', 'sakura-pink'],
      ['sakura-pink', 'chocolate-brown', 'forest-lime', 'amber-orange'],
      ['amber-orange', 'sakura-pink', 'chocolate-brown', 'forest-lime'],
      ['forest-lime', 'amber-orange', 'sakura-pink', 'chocolate-brown'],
      ['ruby-red', 'ruby-red', 'ruby-red', 'ruby-red'], // Completed tube challenge trap!
      [],
      [],
    ],
  },
  {
    id: 105,
    name: 'Secret Chamber: Celestial Zenith',
    isSecret: true,
    difficulty: 'Hidden',
    capacity: 4,
    parMoves: 44,
    tubes: [
      ['ocean-cyan', 'golden-yellow', 'sapphire-blue', 'emerald-green'],
      ['sakura-pink', 'chocolate-brown', 'forest-lime', 'ruby-red'],
      ['emerald-green', 'ocean-cyan', 'golden-yellow', 'sapphire-blue'],
      ['ruby-red', 'sakura-pink', 'chocolate-brown', 'forest-lime'],
      ['sapphire-blue', 'emerald-green', 'ocean-cyan', 'golden-yellow'],
      ['forest-lime', 'ruby-red', 'sakura-pink', 'chocolate-brown'],
      ['golden-yellow', 'sapphire-blue', 'emerald-green', 'ocean-cyan'],
      ['chocolate-brown', 'forest-lime', 'ruby-red', 'sakura-pink'],
      [],
      [],
    ],
  },
];

export function getLevel(levelId: number): LevelConfig {
  // Check if it's a secret level
  if (levelId >= 100) {
    const hidden = HIDDEN_LEVELS.find(l => l.id === levelId);
    if (hidden) return hidden;
  }

  // Check curated levels
  const curated = CURATED_LEVELS.find(l => l.id === levelId);
  if (curated) return curated;

  // Otherwise procedural solvable level
  const numColors = Math.min(3 + Math.floor(levelId / 5), 8);
  const emptyTubes = levelId > 15 ? 2 : 2;
  return generateProceduralLevel(levelId, numColors, emptyTubes, 4);
}
